/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#b9eed5",
        "success-green": "#2D5F4C",
        "on-surface-variant": "#5a413b",
        "on-tertiary-fixed": "#002116",
        "inverse-surface": "#333025",
        "on-error-container": "#93000a",
        "primary-container": "#c73e1d",
        secondary: "#865300",
        "on-secondary": "#ffffff",
        outline: "#8e706a",
        "outline-variant": "#e2bfb7",
        "primary-fixed-dim": "#ffb4a3",
        "on-primary-container": "#ffefeb",
        "on-tertiary-container": "#c8fee5",
        "secondary-fixed": "#ffddb8",
        "tv-bezel": "#1A2E35",
        "surface-bright": "#fff9ec",
        "on-primary": "#ffffff",
        primary: "#a42504",
        "on-error": "#ffffff",
        tertiary: "#2d5f4c",
        "inverse-primary": "#ffb4a3",
        "on-tertiary": "#ffffff",
        "on-surface": "#1e1c12",
        "surface-container-high": "#eee8d7",
        "error-container": "#ffdad6",
        "surface-container": "#f4eddd",
        "on-tertiary-fixed-variant": "#1c4f3d",
        "surface-dim": "#e0dac9",
        "on-secondary-container": "#6b4200",
        "on-primary-fixed-variant": "#8a1b00",
        "tertiary-container": "#467864",
        "sand-divider": "#FAD9A0",
        "secondary-container": "#ffa92e",
        "error-red": "#C73E1D",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        surface: "#fff9ec",
        "on-secondary-fixed-variant": "#653e00",
        "secondary-fixed-dim": "#ffb960",
        background: "#fff9ec",
        "on-secondary-fixed": "#2b1700",
        "surface-container-low": "#faf3e2",
        "tertiary-fixed-dim": "#9dd2ba",
        "surface-tint": "#b02e0d",
        "inverse-on-surface": "#f7f0df",
        "on-primary-fixed": "#3d0700",
        "surface-variant": "#e9e2d2",
        "on-background": "#1e1c12",
        "surface-container-highest": "#e9e2d2",
        "primary-fixed": "#ffdad2",
      },
      spacing: {
        base: "8px",
        "container-padding": "1.5rem",
        "component-gap": "1rem",
        "section-gap": "2rem",
      },
      rotate: {
        "1.5": "1.5deg",
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Anton", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Anton", "sans-serif"],
        "display-lg-mobile": ["Anton", "sans-serif"],
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Anton", "sans-serif"],
        "headline-sm-mobile": ["Anton", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm-mobile": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-sm-mobile": ["20px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
